# WARNING: This file is auto-generated by `nixos-generate-config` on the WSL host.
# After the first boot, run:
#   sudo nixos-generate-config --dir /etc/nixos
# Then replace this file with the generated one.
#
# WSL typically needs no special disk configuration since the filesystem
# is provided by the Windows host.

{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "ehci_pci"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/PLACEHOLDER";
    fsType = "ext4";
  };
}
