creation_rules:
  - path_regex: secrets\.ya?ml$
    key_groups:
      - age:
          # Your local development key
          - "age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g"
          # Target machine key (add after generating)
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMXtQHWgKc2ZXb0R06P2HUBuNeO1it8HWu12OLHP8vgB llm01"
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPGe70V1923+UAbbB9himWWvqjv+vvEp9HE3J7j4KJvp ryzen7"
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMS+VBOhEKYOEc+SSITquXS7NHsQko5Rwr0WwwCZK99c k8s-node03"
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILqHhvkuxO21tW+rsT7LgPmxuvwAOHgnDT+L9gh6KFtE k8s-pi01"
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC4Qqjk15y9JeenuMnCmqcxFTYTFk5Xc55cyoXdsrkRc k8s-pi02"
          # Bootstrap key
          - age1rlvgte0l7225vqdusvkzmdqmsyfd3u255rfy7ku93xx99k4vldsqhxnyxx

