creation_rules:
  - path_regex: secrets\.ya?ml$
    key_groups:
        - age:
            # Your local development key
            - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJAxtDTZvN/YqOQC1nOGahb/qLp35iYnBTPaGld6/N6k javier@Javiers-MacBook-Air.local"
            # Target machine key (add after generating)
            - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMXtQHWgKc2ZXb0R06P2HUBuNeO1it8HWu12OLHP8vgB llm01"
            - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPGe70V1923+UAbbB9himWWvqjv+vvEp9HE3J7j4KJvp ryzen7"
            - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMS+VBOhEKYOEc+SSITquXS7NHsQko5Rwr0WwwCZK99c k8s-node03"
            - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBEjTLTKB2sZ7jehQ85kUCYVb2326IGcQn/CZkjROsIm k8s-node04"
            # Bootstrap key
            - age1rlvgte0l7225vqdusvkzmdqmsyfd3u255rfy7ku93xx99k4vldsqhxnyxx
